spring:
  datasource:
    url: jdbc:h2:mem:devDB
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
  error:
    include-message: true

jwt:
  secret: SECRET_KEY
  validity: 10 * 1000 * 60 * 60